# Generated by Django 5.0.4 on 2024-05-04 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonico', models.CharField(max_length=10)),
                ('nomeExame', models.CharField(max_length=100)),
                ('mneapoio', models.CharField(max_length=10)),
                ('valor', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12)),
                ('nomePaciente', models.CharField(max_length=200)),
                ('dataAtendimento', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exames', models.ManyToManyField(related_name='atendimentos', to='atendimentos.exame')),
            ],
        ),
    ]
